services:
  processor-pg:
    image: postgres:16-alpine
    ports:
      - "5482:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=processor
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
