_format_version: "3.0"
_transform: true

services:
  - name: processor
    url: http://host.docker.internal:3333
    protocol: http
    host: host.docker.internal
    port: 3333
    path: /
    routes:
      - name: api-processor
        protocols:
          - http
          - https
        paths:
          - /processor

  - name: catalog
    url: http://host.docker.internal:3334
    protocol: http
    host: host.docker.internal
    port: 3334
    path: /
    routes:
      - name: api-catalog
        protocols:
          - http
          - https
        paths:
          - /catalog

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Content-Type
        - Content-Length
        - Authorization
